apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      run: poi
  replicas: 1
  template:
    metadata:
      labels:
        run: poi
    spec:
      containers:
      - name: poi
        image: registryqln8975.azurecr.io/tripinsights/poi:1.0
        volumeMounts:
        - name: poi-kv
          mountPath: /secrets
          readOnly: true
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
      volumes:
      - name: poi-kv
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds                  # [OPTIONAL] not required if using Pod Identity
          options:
            usepodidentity: "false"        # [OPTIONAL] if not provided, will default to "false"
            keyvaultname: "team2keyvault"               # the name of the KeyVault
            keyvaultobjectnames: SQL-USER;SQL-PASSWORD;SQL-FDQN    # list of KeyVault object names (semi-colon separated)
            keyvaultobjecttypes: secret;secret;secret  # list of KeyVault object types: secret, key or cert (semi-colon separated)
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
            resourcegroup: "teamResources"              # [REQUIRED FOR < v0.0.14] the resource group of the KeyVault
            subscriptionid: "4fd85f80-d7c8-46d0-9b86-ba3b7402377a"             # [REQUIRED FOR < v0.0.14] the subscription ID of the KeyVault
            tenantid: "6065c98a-b00b-42a9-a805-f81775ebdf92"                   # the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
  labels:
    run: poi
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: poi
