apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
spec:
  selector:
    matchLabels:
      run: user-java
  replicas: 1
  template:
    metadata:
      labels:
        run: user-java
  spec:
    containers:
      - name: user-java
        image: registryqln8975.azurecr.io/tripinsights/user-java:1.0
        volumeMounts:
        - name: user-java-kv
          mountPath: /secrets
          readOnly: true
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
    volumes:
    - name: user-java-kv
      flexVolume:
        driver: "azure/kv"
        secretRef:
          name: kvcreds
        options:
          usepodidentity: "false"
          keyvaultname: "team2keyvault"
          keyvaultobjectnames: SQL-USER;SQL-PASSWORD;SQL-FDQN
          keyvaultobjecttypes: secret;secret;secret
          keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"
          resourcegroup: "teamResources"
          subscriptionid: "4fd85f80-d7c8-46d0-9b86-ba3b7402377a"
          tenantid: "6065c98a-b00b-42a9-a805-f81775ebdf92"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  labels:
    run: user-java
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: user-java
