apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      run: userprofile
  replicas: 1
  template:
    metadata:
      labels:
        run: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryqln8975.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: tripinsightsdb
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api
  labels:
    run: userprofile
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: userprofile
